### ISSUE TITLE
6. As a user, I want to see a Asset Pie Chart and total Assets number on the Dashboard page

### ISSUE THREAD

**Issue by shangguanwang** [shangguanwang/FlowFi#6]
## Summary
Users need to be able to see their assets sliced by `type` in a donut pie chart 

## Acceptance Criteria
- [x] The `Home` page displays a donut pie chart based on the data in the `Assets` page

**Comment by shangguanwang** [comment]
## WIP
- [x] use `recharts` to create a donut pie chart based on test data

## Todo
- [x] Study Redux to pass data across different components

## Assets Pie Chart Screenshot
![Assets Pie Chart after](https://github.com/shangguanwang/FlowFi/assets/24996005/e8f0936a-8a0f-486d-8a97-1b10ae4656a9)

**Comment by shangguanwang** [comment]
## Approach
1. Create `redux/assetsSlice.js` and replace useState in `Assets.tsx` with Redux global state management
2. Import assetsData into `PieCharts.tsx` and map it to chartData array, which is a format that recharts required to create the pie chart.
3. Create `NumberCard.tsx` component and add it to Dashboard page

## Dashboard After
![piechart-after](https://github.com/shangguanwang/FlowFi/assets/24996005/ab396b55-1a6d-4421-a3d5-35429a2c5a73)
